name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenvs-path: ~/my-custom-path
        installer-parallel: true
    - name: Gerar Documentação
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install breathe
        cd Sphinx
        make html
    - name: Testes
      run: |
        pip install pytest
        pytest tests
    - name: Build
      run: |
        cd poetry
        poetry build